basePath: /api/v1
definitions:
  structure.CreateEventRequest:
    properties:
      activities:
        type: string
      admin_id:
        type: string
      deadline:
        type: string
      description:
        type: string
      end_date:
        type: string
      event_image:
        type: string
      event_name:
        type: string
      location_id:
        type: string
      organizer_id:
        type: string
      participant_fee:
        type: number
      start_date:
        type: string
      status:
        type: string
    required:
    - activities
    - admin_id
    - deadline
    - description
    - end_date
    - event_name
    - location_id
    - organizer_id
    - participant_fee
    - start_date
    - status
    type: object
  structure.CreateEventResponse:
    properties:
      event_id:
        type: string
    type: object
  structure.TestResponse:
    properties:
      message:
        type: string
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server Mai-Roi-Ra api gateway.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Mai-Roi-Ra Swagger API
  version: "1.0"
paths:
  /events:
    post:
      consumes:
      - application/json
      description: Create a new event with the provided details.
      parameters:
      - description: Create Event Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/structure.CreateEventRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/structure.CreateEventResponse'
        "400":
          description: Bad Request
          schema:
            type: object
        "500":
          description: Internal Server Error
          schema:
            type: object
      summary: Create new event
      tags:
      - events
  /test:
    get:
      consumes:
      - application/json
      description: Get a test message
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/structure.TestResponse'
      summary: GetTest
      tags:
      - Test
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
