basePath: /api/v1
definitions:
  controllers.TestResponse:
    properties:
      message:
        type: string
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server Mai-Roi-Ra api gateway.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Mai-Roi-Ra Swagger API
  version: "1.0"
paths:
  /test:
    get:
      consumes:
      - application/json
      description: Get a test message
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.TestResponse'
      summary: GetTest
      tags:
      - Test
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
