version: '3.9'

services:
  event_db:
    image: mongo
    container_name: event_db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: rRLkKLMbDmEqNH0E
    ports:
      - "2000:27017"
    command: "--bind_ip_all"
