FROM alpine:latest

RUN apk add --no-cache curl postgresql-client

WORKDIR /migrations

RUN curl -L https://github.com/golang-migrate/migrate/releases/download/v4.17.0/migrate.linux-amd64.tar.gz -o migrate.tar.gz && \
    tar -xzvf migrate.tar.gz && \
    ls && \
    mv migrate /usr/local/bin/migrate && \
    chmod +x /usr/local/bin/migrate && \
    rm migrate.tar.gz

COPY ./migrations /migrations

CMD ["migrate", "--help"]
