# # Use the official Golang image as a base image
FROM golang:latest

# # Set the working directory inside the container
# WORKDIR /app

# RUN go install github.com/cosmtrek/air@v1.41.0

# COPY go.mod go.sum ./
# RUN go mod download

# COPY . ./

# CMD ["~/.air", "-c", ".air.toml"]